[package]
name = "typervox"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
alsa = "0.10"
ct2rs = { version = "0.9.14", default-features = false, features = ["whisper", "hub", "tokenizers", "ruy"] }

[patch.crates-io]
sentencepiece-sys = { path = "patches/sentencepiece-sys-0.12.0" }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
